org: kylepls
app: chrome-imager
service: chrome-imager

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1 

plugins:
  - serverless-plugin-typescript
  - serverless-offline
#  - serverless-plugin-chrome

#package:
#  exclude:
#    - node_modules/puppeteer/.local-chromium/**

functions:
  imager:
    handler: src/handlers/chrome-handler.chromeHandler
    memorySize: 1536MB
    timeout: 300
    events:
      - http:
          path: /imager
          method: POST
          cors: true